# Generated by Django 3.2.25 on 2025-05-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_auto_20250518_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:00 - 8:55', '8:55 - 9:50'), ('10:10 - 11:05', '11:05 - 12:00'), ('12:00 - 12:55', '12:55 - 1:50'), ('2:10 - 3:05', '3:05 - 4:00'), ('4:00 - 4:55', '4:55 - 5:50')], default='11:30 - 12:30', max_length=50),
        ),
    ]
